### ISSUE TITLE
Plot versus distance along transect

### ISSUE THREAD

**Issue by kakearney** [lnferris/ocean_data_tools#24]
This issue is part of the JOSS review (openjournals/joss-reviews#2497)

For the section-plotting tools, you offer the option to place either latitude or longitude along the x-axis.  Distance-along-transect would be another obvious candidate here, especially when section-plotting circuitous routes that may double back on themselves.

**Comment by lnferris** [comment]
Thanks for the suggestion! I have added this feature to bathymetry_section and general_section.
