### ISSUE TITLE
Markdown documentation vs Matlab docs

### ISSUE THREAD

**Issue by kakearney** [lnferris/ocean_data_tools#28]
This issue is part of the JOSS review (openjournals/joss-reviews#2497)

You've written some nice markdown documentation for most of the functions, which can be viewed online (or with a markdown editor/viewer, but I would not assume users have access to the latter).  However, these are not compatible with Matlab's own documentation viewer.  It would be very beneficial to users if you added .html versions of these documentation files and made them accessible via Matlab's `doc` command (see https://www.mathworks.com/help/matlab/matlab_prog/display-custom-documentation.html).

**Comment by lnferris** [comment]
I have added Matlab documentation. 

<img width="1174" alt="Screen Shot 2020-09-25 at 2 21 28 AM" src="https://user-images.githubusercontent.com/24570061/94233588-21198b00-fed6-11ea-8700-ef0ff81fb6e6.png">
